config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy, :show]

  resources :subs
  resources :posts do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:destroy, :create, :edit, :update, :show] do
    resources :comments, only: [:new]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author, :post, presence: true

  belongs_to :post, inverse_of: :comments
  belongs_to :author, class_name: :User, inverse_of: :comments
  belongs_to :parent, class_name: :Comment, foreign_key: :parent_id

  has_many :child_comments,
   foreign_key: :parent_id,
   class_name: :Comment

end

app/models/cross_post.rb
class CrossPost < ActiveRecord::Base
  validates :sub, :post, presence: true

  belongs_to :sub, inverse_of: :cross_posts
  belongs_to :post, inverse_of: :cross_posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :subs, :author, presence: true


  has_many :cross_posts
  has_many :subs, through: :cross_posts, source: :sub
  belongs_to :author, class_name: "User", inverse_of: :posts
  has_many :comments, inverse_of: :post

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator, class_name: "User"

  has_many :cross_posts
  has_many :posts, through: :cross_posts
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: :true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, uniqueness: true

  has_many :posts
  has_many :subs
  has_many :comments, foreign_key: :author_id

  attr_reader :password


  after_initialize :ensure_session_token

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user
      user.is_password?(password) ? user : nil
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
    @current_user ? @current_user : nil
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout!
    user = current_user
    user.reset_session_token!
    session[:session_token] = nil
  end

  def ensure_ownership
    user = User.find(params[:id])
    if current_user.id != user.id
      redirect_to root_url
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    @comment.parent_id = params[:comment_id]
    render :new
  end

  def create
    post_id = Comment.find(comment_params[:parent_id]).post_id
    # comment_params[:post_id]||= post_id
    c = comment_params
    c[:post_id]=post_id
    @comment = Comment.new(c)
    @comment.author_id = current_user.id
    #
    # @comment.post_id ||= post_id
    if @comment.save!
      redirect_to post_url(post_id)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @comment.errors.full_messages
      render :new
    end
  end

  def destroy

  end

  def edit

  end

  def update

  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_post_owner, only: [:edit, :update]

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save!
      redirect_to post_url(@post)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @subs = Sub.all
    @author = @post.author
    @all_comments = @post.comments
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @post.errors.full_messages
      render :edit
    end
  end

  def ensure_post_owner
    @post = Post.find(params[:id])
    if current_user.id != @post.author_id
      redirect_to subs_url
    end
  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :url, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :ensure_ownership, only: [:show]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:username],user_params[:password])
    if @user
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors]||=[]
      flash.now[:errors] << "Unknown username/password combination"
      render :new
    end
  end

  def destroy
    logout!
    redirect_to root_url
  end

  def show
    @user = User.find(params[:id])
    if @user
      render :show
    else
      redirect_to root_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_sub_ownership, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save!
      redirect_to subs_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors]||=[]
      flash.now[:errors] << @sub.errors.full_messages
      render :edit
    end
  end

  def ensure_sub_ownership
    @sub = Sub.find(params[:id])
    if current_user.id != @sub.moderator_id
      redirect_to subs_url
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_ownership, only: [:show]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save!
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors]||=[]
      flash.now[:errors] << @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @user
      render :show
    else
      redirect_to root_url
    end
  end



  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\"
    value\"#{form_authenticity_token}\">".html_safe
  end

  def slice_comment(content)
    comment = content[0..10]
    comment << "..." if content.length > 10
    comment
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<form action="<%=comments_url%>" method="post">
  <input type="hidden" name="comment[post_id]" value="<%=@comment.post_id%>">
  <input type="hidden" name="comment[parent_id]" value="<%=@comment.parent_id%>">
  <%= auth_token %>
  <label for="Body">Body</label>
  <br>
  <textarea id="Body" name="comment[content]" rows="8" cols="10"> <%=@comment.content%> </textarea>
  <br>
  <button>Submit</button>
</form>

app/views/comments/new.html.erb
<h1>New Comment!</h1>

<%= render "form", comment: @comment %>

app/views/comments/show.html.erb
<h1>  <%= slice_comment(@comment.content) %> </h1>

<p>
  <strong>Reply to this comment:</strong>
</p>

<%= render "form", comment: @comment  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user  %>
<%= link_to "Create a sub!", new_sub_url %>
<br>
<%= link_to "All subs", subs_url %>
<p><%= current_user.username %></p>
<%= button_to "Logout" , session_url, method: :delete %>
<% else %>
<%= link_to "Sign in", new_session_url%>
<% end  %>

<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
<a href="<%=new_comment_comment_url(comment)%>"><%=slice_comment(comment.content)%></a>
<ul>
  <% all_comments.each do |comment2| %>
    <% if comment2.parent_id == comment.id %>
      <li><a href="<%=new_comment_comment_url(comment2)%>"><%=slice_comment(comment2.content)%></a></li>
    <% end %>
  <% end %>
</ul>

app/views/posts/_form.html.erb
<h1><%=message%></h1>


<form action="<%=action%>" method="post">
<%= auth_token %>
<input type="hidden" name="_method" value="<%=method%>">

<label for="title">Title:</label>
<input id="title" type="text" name="post[title]" value="<%=@post.title%>">
<br>

<label for="url">URL:</label>
<input id="url" type="text" name="post[url]" value="<%=@post.url%>">
<br>

<label for="textarea">Content:</label>
<br>
<textarea id="textarea" name="post[content]" rows="8" cols="40"> <%= @post.content %> </textarea>
<br>
<input type="hidden" name="sub[title][]" value="">
<% @subs.each do |sub| %>
  <input id="<%=sub.title%>"
  type="checkbox"
   name="post[sub_ids][]"
   value="<%=sub.id%>"
   <%="checked" if post.sub_ids.include?(sub.id)%>>
   <label for="<%sub.title%>"><%=sub.title%></label>
   <br>
<% end %>
<br>
<button>Submit</button>

</form>

app/views/posts/edit.html.erb
<%= render 'form', action: post_url, post: @post, message: "Edit post", subs: @subs, method: "patch" %>

app/views/posts/new.html.erb
<%= render 'form', action: posts_url, message: "Create new post", post: @post, method: "post", subs: @subs %>

app/views/posts/show.html.erb
<h1><%=@post.title%> by <%=@author.username%></h1>

<h3>Content:</h3>

<p>
  <%=@post.content %>
</p>

<h4>Subs</h4>

<ul>
  <%@subs.each do |sub| %>
    <li><a href="<%=sub_url(sub)%>"><%=sub.title%></a></li>
  <% end %>
</ul>

<h3>Comments</h3>
<%= link_to "Comments on this post:", new_post_comment_url(@post)  %>
<br>

<% @all_comments.each do |comment| %>
  <% if comment.parent_id.nil? %>
    <%= render 'comment', comment: comment, all_comments: @all_comments %>
  <% end %>
<% end %>

<% if current_user.id == @post.author_id %>
<%= link_to "Edit post", edit_post_url(@post) %>
<% end %>

app/views/shared/_form.html.erb
<form action="<%=action%>" method="post">
  <%= auth_token %>
  <label for="name">Name</label>
  <input type="text" name="user[username]" value="<%=user.username%>">
  <br>

  <label for="password">Password</label>
  <input type="password" name="user[password]" value="<%=user.password%>">
  <br>

  <button>Submit</button>
</form>

app/views/subs/_form.html.erb
<h1> <%= message %></h1>
<form action="<%=action%>" method="post">
  <input type="hidden" name="_method" value="<%=method%>">
  <%= auth_token %>

  <label for="title">Title</label>
  <input id="title" type="text" name="sub[title]" value="<%=@sub.title%>">
  <br>

  <label for="desc">Description</label>
  <textarea id="desc" name="sub[description]" rows="8" cols="30"><%=@sub.description%></textarea>

  <button>Submit</button>
</form>

app/views/subs/edit.html.erb
<%= render "form", action: sub_url(@sub), method: "patch", message: "Edit your sub", sub: @sub  %>

app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
  <% @subs.each do |sub| %>
  <li><a href="<%=sub_url(sub)%>"><%=sub.title%></a></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<%= render "form",action: subs_url, message: "Create new sub", method: "post", sub: @sub %>

app/views/subs/show.html.erb
<h1><%=@sub.title%></h1>
<h3>Description</h3>
<p><%=@sub.description%></p>
<%= link_to "Make new post", new_post_url %>
<% if current_user.id == @sub.moderator_id %>
<br>
<%= link_to "Edit sub", edit_sub_url(@sub) %>
<% end %>
<ul>
  <% @posts.each do |post| %>
    <li> <a href="<%=post_url(post)%>"><%=post.title%></a> </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New user!</h1>
<%= render 'shared/form', head_message: "Create user",  action: users_url, user: @user %>

app/views/users/show.html.erb
<h1> Hi, <%= @user.username %>   </h1>